// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4388.HelloMicrobot;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.CANTalon;
import edu.wpi.first.wpilibj.RobotDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static CANTalon driveTrainFrontLeftMotor;
    public static CANTalon driveTrainBackLeftMotor;
    public static CANTalon driveTrainFrontRightMotor;
    public static CANTalon driveTrainBackRightMotor;
    public static RobotDrive driveTrainFourWheelDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainFrontLeftMotor = new CANTalon(2);
        LiveWindow.addActuator("DriveTrain", "Front Left Motor", driveTrainFrontLeftMotor);
        
        driveTrainBackLeftMotor = new CANTalon(3);
        LiveWindow.addActuator("DriveTrain", "Back Left Motor", driveTrainBackLeftMotor);
        
        driveTrainFrontRightMotor = new CANTalon(4);
        LiveWindow.addActuator("DriveTrain", "Front Right Motor", driveTrainFrontRightMotor);
        
        driveTrainBackRightMotor = new CANTalon(5);
        LiveWindow.addActuator("DriveTrain", "Back Right Motor", driveTrainBackRightMotor);
        
        driveTrainFourWheelDrive = new RobotDrive(driveTrainFrontLeftMotor, driveTrainBackLeftMotor,
              driveTrainFrontRightMotor, driveTrainBackRightMotor);
        
        driveTrainFourWheelDrive.setSafetyEnabled(true);
        driveTrainFourWheelDrive.setExpiration(0.1);
        driveTrainFourWheelDrive.setSensitivity(0.5);
        driveTrainFourWheelDrive.setMaxOutput(1.0);
        driveTrainFourWheelDrive.setInvertedMotor(RobotDrive.MotorType.kFrontLeft, true);
        driveTrainFourWheelDrive.setInvertedMotor(RobotDrive.MotorType.kRearLeft, true);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
